# Generated by Django 2.1.7 on 2019-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binancecoins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binancecoinlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='binancecoinlist',
            name='coinsymbol',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Coin'),
        ),
    ]
